### ISSUE TITLE
Damage Numbers and inspections

### ISSUE THREAD

**Issue by miyho** [Hypnootize/Broesel-Old#1]
Whenever i try to inspect what is someone wearing/using it only half of the inspection tab (on the down right corner) shows up, and ive tried to change the damage number font to "surface28shadow" but it doesnt work in any way.

**Comment by miyho** [comment]
![image](https://github.com/Hypnootize/Broesel-Old/assets/87745343/8d6c2eb3-e32b-4091-8a84-62eec521337c)
heres an example

**Comment by Hypnootize** [comment]
The inspect panel has been fixed with https://github.com/Hypnootize/Broesel-Old/commit/6b6954d8c9ad6c9de2a9b566e0b8bb07c97eef7c
As for `"surface28shadow"`, it doesn't work as it is missing inside `ClientScheme.res` so if you wish to use that size for your damage you will have to create a new font entry for it in the `ClientScheme.res`, should be an easy process as you can simply clone the `Surface24Shadow` element [HERE](https://github.com/Hypnootize/Broesel-Old/blob/master/resource/ClientScheme.res#L704-L715) and edit it to be `"surface28shadow"` with `"tall" "28"`
